# Generated by Django 4.2.4 on 2023-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('bgroup', models.CharField(max_length=3)),
                ('donorid', models.CharField(max_length=10, unique=True)),
                ('more', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
