# Generated by Django 4.2.4 on 2023-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregister',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
