# Generated by Django 4.2.7 on 2023-12-07 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_donorregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregister',
            name='donorid',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='donorregister',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
