# Generated by Django 4.2.7 on 2023-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_donorregister_donorid_alter_donorregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregister',
            name='donorid',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
