# Generated by Django 4.2.7 on 2023-12-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_donorregister_donorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorregister',
            name='email',
        ),
    ]
