# Generated by Django 4.2.7 on 2024-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_donorregister_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregister',
            name='village',
            field=models.CharField(default='Saddowala Uncha', max_length=50),
            preserve_default=False,
        ),
    ]
