# Generated by Django 4.2.7 on 2024-01-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_donorregister_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('org_head', models.CharField(max_length=50)),
                ('org_address', models.CharField(max_length=50)),
                ('org_email', models.EmailField(max_length=254)),
                ('head_ph', models.CharField(max_length=11)),
                ('org_logo', models.FileField(upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='donorregister',
            name='certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorregister',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organizationregister'),
        ),
    ]
